// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDir() {
  return window['go']['main']['App']['GetDir']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFiles(arg1) {
  return window['go']['main']['App']['SaveFiles'](arg1);
}

export function UploadFiles(arg1) {
  return window['go']['main']['App']['UploadFiles'](arg1);
}
