// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tools} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetDir():Promise<string>;

export function Log(arg1:Array<any>):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<Error>;

export function SaveFile(arg1:string,arg2:string):Promise<Error>;

export function SaveFiles(arg1:Array<tools.SaveFileArg>):Promise<Error>;

export function UploadFiles(arg1:tools.UploadFileArg):Promise<string>;
